import os
basedir = os.path.abspath(os.path.dirname(__file__))

SECRET_KEY = 'XXXXXXXXXXXX'
#PORT = 5000

SQLALCHEMY_DATABASE_URI = 'XXXXXXXXXXXXXX'
SQLALCHEMY_MIGRATE_REPO = 'XXXXXXXXXXXXXX'

S3_LOCATION = 'XXXXXXXXXX'
S3_KEY = 'XXXXXXXXXX'
S3_SECRET = 'XXXXXXXXXX'
S3_UPLOAD_DIRECTORY = 'XXXXXXXXXX'
S3_BUCKET = 'XXXXXXXXXX'



